### ISSUE TITLE
Personal Training + Consultation pages

### ISSUE THREAD

**Issue by hfridrik** [Beyond-Skills-Training-Global/bst-tw-design#35]
Few questions from the DESIGN part:

_“Coaching Consultations” page_

1.	I see that the title (with the photo on the background) seems to be smaller than I imagined. Is it possible to increase the font a little bit for the desktop version?

2.	The title (with claws) is not in upper-case letters, but it should be

3.	Right after the “Submit” button, the grey area should be prolonged a little so that it looks balanced with the top 

_“Personal Training” page:_

1.	Right after the “Submit” button, the grey area should be prolonged a little so that it looks balanced with the top 

Few questions from the RESOLUTION part:

Looking from the browser to the resolution 375 x 812 it looks like the “leave the message” box goes beyond the required parameters… However, looking from my phone with a resolution 375 x 812 – the “message” box looks fine. 

Is it somehow a mistake? or is it a normal phenomenon? :D

![2022-07-15 10_10_46-Untitled-1_ @ 66 67 % (CMYK_Preview)](https://user-images.githubusercontent.com/109089673/179181720-11dcaaeb-7cf9-4965-b80d-0dacddd4eeb5.png)

**Comment by rajdevkar** [comment]
@hfridrik I think this issue is resolved can you check and close this issue.

**Comment by hfridrik** [comment]
@rajdevkar thank you. Still have some comments:
[Fianl Comments.pdf](https://github.com/Beyond-Skills-Training-Global/bst-tw-design/files/9233250/Fianl.Comments.pdf)

**Comment by rajdevkar** [comment]
Okay will check.

**Comment by rajdevkar** [comment]
@hfridrik Please check.

**Comment by hfridrik** [comment]
Looks better, just a few things I've noticed. @rajdevkar 

Desktop only:

1.	Features Page
Above the title “BST.COACH” should be all in caps

2.	Get to Know Us
2.1	The yellow triangles are not on the same level… was is done on purpose?
![Get to Know us](https://user-images.githubusercontent.com/109089673/182856756-41dcece1-453b-42c3-a78a-d3b2160ed6e7.png)

2.2 Our Goal: the sentences are still not extended to 2 lines in the desktop version. I believe it is possible.
